### ISSUE TITLE
siri integration degraded, then completely stopped working with ios 14.6

### ISSUE THREAD

**Issue by jmechler** [koryhutchison/homebridge-opensprinkler-api#3]
I'm not sure if this an issue with the plugin or some other part of my setup.

My use case is a little strange. I have a zone on my open sprinkler controller hooked up to a relay that "pushes" my garage door opener button. I've had a rube goldberg shortcut that ended up calling a URL, but it's really unreliable with phone not always connecting to wifi quickly, etc.

I decided to try homebridge and this plugin, with my homepod as the home hub, and it started out working great with siri. I defined a "valve" called "Garage Door", could say "Hey Siri, turn on the garage door" as I pulled into the alley, and it worked every time.

At some point that stopped working, but I could say "Hey Siri, water the garage door" instead

Finally, controlling via Siri stopped working all together, I think when I upgraded to ios 14.6,

It still works if I manually use the button in the Home App.

Also, it seems like Siri knows about it a little because I can say "Hey Siri, What valves does my sprinkler system have", and Siri will answer "Garage Door is not being watered"

However, any attempt to control ends up with "Sorry, I didn't hear back from your devices. Make sure you're on the same Wi-Fi or have remote access setup in the Home App". This is the same on my iphone, ipad, and mac, but they all can then control using the interface in the Home app.

```
I don't know if there are any relevant logs.
```

**Plugin Config:**

```
{
    "bridge": {
        "name": "Homebridge F0B0",
        "username": "0E:89:E4:XX:XX:XX",
        "port": XXXXX,
        "pin": "934-XX-XXX",
        "advertiser": "ciao",
        "bind": [
            "ens3"
        ]
    },
    "accessories": [
        {
            "name": "Test",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Sink",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "password": {
                "md5": "XXXXXXXXXX"
            },
            "valves": [
                {
                    "name": "Garage Door",
                    "defaultDuration": 1
                }
            ],
            "host": "mysprinkler.wherever.com:8080",
            "pollInterval": 15,
            "platform": "HomebridgeOpenSprinklerApi"
        }
    ]
}
```

**Environment:**

* **Plugin Version**: 1.1.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: v14.17.0
* **NPM Version**: 6.14.13
* **Operating System**: Ubuntu 20.04.2
*

**Comment by koryhutchison** [comment]
First off, thanks for trying out my plugin! I've tried hard to make things as simple as possible. 

Yeah your situation is rather tricky. The fact that you say that everything within the normal Home app works fine, leads me to believe that this is just an issue with Siri recognizing the names of things. A garage door is a specific type of HomeKit accessory, so it's possible that Siri is trying to look for one and isn't finding it. I do have a suggestion though that should work.

As of right now, the Home app doesn't allow you to set up scenes with an irrigation system. But, other apps do let you. I'd suggest you download the Eve app (It's free) and it'll allow you to create a HomeKit Scene for your "Garage door" valve. So you could name it something like, "Open Garage" and another one called "Close Garage". And then you can just use scenes to control that particular valve. In order to avoid any complications with Siri, I'd suggest renaming the garage valve to something unrelated to a garage. 

Let me know if this works or doesn't work for you. But yeah when developing a plugin, we don't have any control on how Siri interacts with it. But I think setting up a scene will work well as it's worked well for me with other Homebridge accessories.

**Comment by koryhutchison** [comment]
It's been 7 days and I haven't heard anything so I'm going to close this. Feel free to reach out if you have any other questions/concerns.

**Comment by cybergrimes** [comment]
fwiw I'll reply since I stumbled on this... there's some kind of issue with Siri and sprinklers in current iOS. I can't get certain commands to work with RainMachine and have seen on Yardian forums that they've submitted bug reports to Apple re: this issue.

https://support.yardian.com/hc/en-us/community/posts/360078194752-Issues-with-Siri-Commands
